# Generated by Django 5.0.2 on 2024-03-13 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userbase',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='userbase',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='userbase',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='userbase',
            name='username',
        ),
    ]
